### PR TITLE
Introduce Benchmarking category + add benchee

### LINKED ISSUE #2212: Add Package "benchee"
Add the Package "benchee" from hex.pm

Link: https://hex.pm/packages/benchee

Description: 
Versatile (micro) benchmarking that is extensible. Get statistics such as:
average, iterations per second, standard deviation and the median.

### PR DESCRIPTION
**Pull request by PragTob**
Fixes #2212

### CODE REVIEW

**Comment by PragTob** [comment]
Build should be fixed by this update, also updated mix.lock (separate commit so you can leave it out if you want to)

**Comment by fladson** [comment]
Thanks for the contribution @PragTob 
I liked the `Benchmarking` addition, we can discuss it's description
`Running code to see how long it takes, which is faster and/or if improvements have been made.`

And yes, I think that the deps update should be in a separate PR

Also, if you could do a rebase it would be better with something like:
`Add benchmarking category`
`Add package benchee`

**Comment by PragTob** [comment]
Well what do you want the description to look like? And sure I can rebase and split out.

**Comment by PragTob** [comment]
Split the mix.lock update out, rebased as wished. Would love to see this go in :) @fladson

**Comment by fladson** [comment]
Thanks @PragTob, sounds good but I don't have merge access, just trying to help out @h4cc with some review and organization... 😃

**Comment by h4cc** [comment]
@fladson As requested, you are now a "Collaborator". Handle that Pull Requests as you like. I tried to merge as much as possible to get the people a "contribution". Fixing typos/newlines/syntax can be done later...

**Comment by fladson** [comment]
Awesome @h4cc! Thank you for the trust.

**Pull request merged**
