### PR TITLE
Add simhash

### LINKED ISSUE #2388: Add Package "simhash"
Add the Package "simhash" from hex.pm

Link: https://hex.pm/packages/simhash

Description: 
Simhash implementation using Siphash and N-grams.

### PR DESCRIPTION
**Pull request by bartolsthoorn**
Closes #2388

### CODE REVIEW

**Comment by fladson** [comment]
Thanks for the contribution @bartolsthoorn but it seems that this package no longer exists
404 at https://github.com/UniversalAvenue/simhash

**Comment by bartolsthoorn** [comment]
Ah an unfortunate typo, it is https://github.com/UniversalAvenue/simhash-ex
Den 5 juli 2016 7:03 em skrev "Fladson Gomes" <notifications@github.com>:

**Comment by fladson** [comment]
Oh, I see 😁 
LGTM

**Comment by bartolsthoorn** [comment]
Ah I thought I made the typo but it was you haha 😁

**Comment by fladson** [comment]
Yes, it was me, the issue has the wrong link, sry

**Comment by bartolsthoorn** [comment]
Ah but that's good to know, then my mix file probably has the wrong link in
it!
Den 5 juli 2016 7:32 em skrev "Fladson Gomes" <notifications@github.com>:

**Comment by bartolsthoorn** [comment]
Fixed, anyway, this is good to merge now.

**Pull request merged**
