### PR TITLE
Add SOAP client which is not abandoned

### PR DESCRIPTION
**Pull request by Liferenko**

### CODE REVIEW

**Comment by Liferenko** [comment]
This library is duplicate checked. 
Plus it was referred in [that issue](https://github.com/h4cc/awesome-elixir/issues/4576) back n 2019.

**Comment by simonewebdesign** [comment]
Thanks - please order alphabetically

**Comment by Liferenko** [comment]
> Thanks - please order alphabetically

done

**Comment by simonewebdesign** [comment]
Thank you!

**Pull request merged**
