### PR TITLE
Add finch HTTP client

### PR DESCRIPTION
**Pull request by bdusauso**
Finch: [https://github.com/keathley/finch](https://github.com/keathley/finch)

### CODE REVIEW

**Comment by bdusauso** [comment]
This issue is related: [https://github.com/h4cc/awesome-elixir/issues/28](https://github.com/h4cc/awesome-elixir/issues/28) but I don't know if it's the same Finch.

**Comment by simonewebdesign** [comment]
Yeah, seems to be the same — thanks!

**Comment by eyalpd-lmt** [comment]
The link https://github.com/keathley/finch which is an empty fork from what it seems.
The original finch repo it seems is https://github.com/sneako/finch

**Comment by simonewebdesign** [comment]
Updated in c3ccc5a

**Pull request merged**
