### PR TITLE
Fix failing build of #4299

### PR DESCRIPTION
**Pull request by LuanGB**
I've kept the original commit of @paralax and added another one to make the build pass, by removing the duplicated entries.

### CODE REVIEW

**Comment by fladson** [comment]
@LuanGB one last thing before I merge, can you check for duplications on some text editor to compare the results?

**Comment by paralax** [comment]
@fladson you consider using awesome_bot to do duplicate detection in CI? https://github.com/TravisToolbox/awesomebot-travis 

i use it on an awsome-list i maintain to great effect.

**Comment by fladson** [comment]
That's a great suggestion @paralax, didn't know about that.
Can you take a look on that @LuanGB ?

**Comment by fladson** [comment]
I see, thanks for checking.
We can stick with this solution for now.
Can you just confirm if it removes the correct dups with a text editor approach?

**Comment by LuanGB** [comment]
Yes! Just checked using `Permute Lines: Unique` with Sublime.

**Pull request merged**
