### PR TITLE
Add jwalk library in response to issue #1319

### PR DESCRIPTION
**Pull request by jr0senblum**
Helper module for working with Erlang representations of JSON: eep 18, map, mochijson-style and proplists representations.

### CODE REVIEW

**Comment by fladson** [comment]
Thanks for the contribution @jr0senblum 
I think we can resume the description to: `Helper module for working with Erlang representations of JSON`

Also you have duplicated commits 😄

**Comment by jr0senblum** [comment]
@fladson do I need to shorten the description or is that something you do? Sorry for
the double commit!

**Comment by fladson** [comment]
@jr0senblum no problem. 
In your rebase to remove the double commit, you can resume the description 😀

**Comment by fladson** [comment]
edited, rebased and merged.

**Pull request closed without merging**
