### PR TITLE
Add cspex

### LINKED ISSUE #1552: Add Package "cspex"
Add the Package "cspex" from hex.pm

Link: https://hex.pm/packages/cspex

Description: 
A library that brings all the CSP joy to the Elixir land.

### PR DESCRIPTION
**Pull request by costaraphael**
Fixes #1552

### CODE REVIEW

**Comment by fladson** [comment]
Thanks for the contribution @costaraphael, you just need to put a `.` on the end of the description.

**Comment by costaraphael** [comment]
Sorry, my bad :sweat_smile: 

Fixed

**Comment by fladson** [comment]
@costaraphael No problem 😄 
Do you mind in doing a rebase/fixup? Thanks

**Comment by costaraphael** [comment]
Ops, looks like another commit got caught up in the rebase. Is it okay or should I just re-do this PR?

**Comment by costaraphael** [comment]
Nevermind, fixed it :sweat_smile:

**Comment by fladson** [comment]
LGTM

**Pull request merged**
