### PR TITLE
Add elixir-tmbundle to editor options

### PR DESCRIPTION
**Pull request by asheren**
## Title
Adds SublimeText plugin to options under editors.

## Description

I noticed there were not any options listed for SublimeText so I added one that
have been both useful and recommended.

## Commit message
Add elixir-tmbundle

### CODE REVIEW

**Comment by fladson** [comment]
Thanks for the contribution @asheren 

You have to put the entries in alphabetic order and we follow a only 1 entry per PR guideline, can you separate this in 2? Thank you.

😁

**Comment by asheren** [comment]
@fladson no problem! I'll make that change now. Thanks for your quick response.

**Comment by asheren** [comment]
@fladson can I ask how you're alphabetizing? I made sure to put the entries onto a spreadsheet and sort alphabetically just to double check but maybe the underscores and hyphens are tripping things up. Thanks!

**Comment by fladson** [comment]
sure @asheren no problem, I think that it should be before `elixir_generator` can you try that and see what happens?

**Comment by asheren** [comment]
@fladson done! thanks. The next addition won't be as painful to review 😄

**Comment by fladson** [comment]
huahua no problem @asheren thanks for the contribution...

**Pull request merged**
