### PR TITLE
Add editor extension vscode-elixir

### PR DESCRIPTION
**Pull request by Fahrradflucht**

### CODE REVIEW

**Comment by Fahrradflucht** [comment]
Anyone an idea why this has failed? I don't really get the logs.

**Comment by fladson** [comment]
Thanks for the contribution @Fahrradflucht 
It is failing because you have a empty space after the dot 😄

**Comment by Fahrradflucht** [comment]
This is way you should never do PRs on a tablet via the browser 😉 

Do you squash anyway or should I do a new commit on a new PR?

**Comment by fladson** [comment]
haha, easy to miss.
we squash, so it's fine.

**Pull request merged**
