### PR TITLE
Add Package "elasticsearch_elixir_bulk_processor"

### LINKED ISSUE #4719: Add Package "elasticsearch_elixir_bulk_processor"
## Title

Add Package "elasticsearch_elixir_bulk_processor"

## Description

Add the Package "elasticsearch_elixir_bulk_processor" from hex.pm.

**Link:** https://hex.pm/packages/elasticsearch_elixir_bulk_processor

**Description:**

Elasticsearch Elixir Bulk Processor is a configurable manager for efficiently inserting data into Elasticsearch. This processor uses genstages for handling backpressure, and various settings to control the bulk payloads being uploaded to Elasticsearch.

### PR DESCRIPTION
**Pull request by sashman**
## Title

Add Package "elasticsearch_elixir_bulk_processor"

## Description

Resolves #4719

## Commit message

Adding elasticsearch_elixir_bulk_processor to the search seciton

### CODE REVIEW

**Comment by Angry-Potato** [comment]
👍

**Comment by simonewebdesign** [comment]
Could you link to the github repo instead?

**Comment by sashman** [comment]
@simonewebdesign done :+1:

**Comment by simonewebdesign** [comment]
Thank you!

**Pull request merged**
