### PR TITLE
Adding shards to ORM and Datamapping

### PR DESCRIPTION
**Pull request by cabol**

### CODE REVIEW

**Comment by fladson** [comment]
Thanks for the contribution @cabol, but maybe the https://github.com/cabol/exshards fits better in the list, what do you think?

You need to do a rebase to pass the build 😃

**Comment by cabol** [comment]
@fladson thanks! First of all, I'll do the rebase to pass the build as you mentioned. Regarding with  [https://github.com/cabol/exshards]( https://github.com/cabol/exshards) I'm not sure, it is still a prototype wrapper that needs to me improved and also needs more work, I'd like to add it later, but the core which is [shards]( https://github.com/cabol/shards) is ready and next release coming. Anyways, let me know your thoughts about it!!

**Comment by cabol** [comment]
Done! build is ok now :) !!

**Comment by fladson** [comment]
I see @cabol, lets wait for @h4cc input on this

**Comment by fladson** [comment]
Resolves #2430

**Pull request merged**
