### PR TITLE
Added simple_bayes

### PR DESCRIPTION
**Pull request by fredwu**
:)

### CODE REVIEW

**Comment by fladson** [comment]
Thanks for the contribution @Kentoseth 
But you have two entries, so you need to remove one of them, probably the one under `Statistics`

**Comment by fredwu** [comment]
@fladson Done!

**Comment by fladson** [comment]
thanks @fredwu, I think you can also remove this `(a.k.a. [Naive Bayes](https://en.wikipedia.org/wiki/Naive_Bayes_classifier))`

**Comment by fladson** [comment]
I think that just `A Simple Bayes implementation in Elixir.` is enough. :smile:

**Comment by fredwu** [comment]
@fladson I could, although this is actually part of the library's description, as Naive Bayes is a better known name. Should I remove just the URL to the Wikipedia page?

**Comment by fredwu** [comment]
How about `A Simple Bayes / Naive Bayes implementation in Elixir.`? :)

**Comment by fredwu** [comment]
@fladson I took the liberty to have it changed to `A Simple Bayes / Naive Bayes implementation in Elixir.`... hopefully this will suffice.

**Comment by fladson** [comment]
resolves #2460

**Pull request merged**
