### PR TITLE
Removing broken link

### PR DESCRIPTION
**Pull request by krolow**
It's seems the project was removed/or/moved (https://github.com/pigmej/exelli)

### CODE REVIEW

**Comment by h4cc** [comment]
Thanks. Asked the Author for a new repo link: https://twitter.com/h4cc/status/601387793596702721

**Comment by krolow** [comment]
(y)

**Comment by h4cc** [comment]
Author seems to unavailable. Merging now.

**Comment by h4cc** [comment]
Package is back again! :)

**Pull request merged**
