### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alexfilatov**
Added ueberauth_line - LINE strategy for Ueberauth

### CODE REVIEW

**Comment by fladson** [comment]
Hey @alexfilatov thanks for the contribution.

Could you please put it in alphabetic order and rename the commit msg to `Add ueberauth_line`?

Resolves #2377

**Comment by alexfilatov** [comment]
thanks a lot for the notice! 
it's done, please have a look.

**Comment by fladson** [comment]
Nice and thanks, 
but you still need to change the commit msg to `Add ueberauth_line`, `update readme` it's not a good commit msg, you have to inform which package it's being added 😃

**Comment by alexfilatov** [comment]
sorry about commit message (messed up with the github editor), now it is more informative.

**Comment by fladson** [comment]
rebased and merged

**Pull request closed without merging**
