### PR TITLE
Update README.md - Noizu Labs - Open AI Wrapper

### PR DESCRIPTION
**Pull request by noizu**

### CODE REVIEW

**Comment by simonewebdesign** [comment]
This package doesn't seem to be published on hex.pm?

**Comment by noizu** [comment]
It should be working unless I misspelt something in there,  https://hex.pm/packages/noizu_labs_open_ai  I'll follow up in a bit.

**Comment by noizu** [comment]
yeah im an idiot, updated the readme with the correct name.

**Comment by noizu** [comment]
I'll run through and verify that e2e after morning meetings.

**Pull request merged**
