### PR TITLE
Add Package "ExRiakCS

### PR DESCRIPTION
**Pull request by ayrat555**
Simple elixir wrapper for Riak CS API

### CODE REVIEW

**Comment by ayrat555** [comment]
Can anybody tell me what's the problem with my pull request?

**Comment by h4cc** [comment]
Alphabetical order of package name `ex_riak_cs` please.

**Comment by ayrat555** [comment]
@h4cc thank you!

**Comment by fladson** [comment]
Thanks for the contribution @ayrat555

**Pull request merged**
