### PR TITLE
Add Package "data_morph"

### LINKED ISSUE #2609: Add Package "data_morph"
Add the Package "data_morph" from hex.pm

Link: https://hex.pm/packages/data_morph

Description: 
Create Elixir structs from data

### PR DESCRIPTION
**Pull request by robmckinnon**
Resolves #2609

### CODE REVIEW

**Comment by robmckinnon** [comment]
Not clear to me why the travis build failed.

**Comment by fladson** [comment]
Thanks for the contribution @robmckinnon 
It's failing because it should be before `datastructures` 😁

**Comment by robmckinnon** [comment]
Made the fix, build passing now.

**Comment by h4cc** [comment]
Thanks!

**Pull request merged**
