### PR TITLE
added Bolt.Sips

### PR DESCRIPTION
**Pull request by florinpatrascu**
##Bolt.Sips

Add Package Bolt.Sips

##Description

A Neo4j driver for Elixir, using the Bolt protocol (Neo4j's newest network protocol, designed for high-performance)

##Commit message
Add Bolt.Sips

### CODE REVIEW

**Comment by fladson** [comment]
Thanks for the contribution @florinpatrascu 
What do you think about changing to a shorter description like `Neo4j driver for Elixir wrapped around the Bolt protocol.` ?

**Comment by florinpatrascu** [comment]
Of course, no problem. I was a bit confused about the new format and I thought the description should be more verbose. Definitely, can be as you suggested. Do I have to send another PR? Please advise, ty!!

**Comment by fladson** [comment]
No problem, you can send another commit to this PR...

**Comment by florinpatrascu** [comment]
Thank you!

**Pull request merged**
