### PR TITLE
Awesome additions

### LINKED ISSUE #644: Add Package "fitex"
Add the Package "fitex" from hex.pm

Link: https://hex.pm/packages/fitex

Description: 
FitEx is a Macro-Module which provides a bit of sugar for function definitions.

### PR DESCRIPTION
**Pull request by doomspork**
Hi @h4cc, this includes two libraries and one resource.  As such, it closes #644 and #645.

### CODE REVIEW

**Comment by doomspork** [comment]
Now including #647 too.

**Comment by h4cc** [comment]
Won-der-full!

**Comment by doomspork** [comment]
Thanks!

**Comment by jclem** [comment]
Hey, thanks @doomspork! That was fast.

**Comment by doomspork** [comment]
Thank _you_ for your contribution @jclem, glad to help out :grinning:

**Pull request merged**
