### PR TITLE
Add Spawn

### PR DESCRIPTION
**Pull request by sleipnir**
Hi, this repository is amazing.
I would like to add the Spawn framework to the Actors list

### CODE REVIEW

**Comment by simonewebdesign** [comment]
could you put it in alphabetical order please?

**Comment by sleipnir** [comment]
> could you put it in alphabetical order please?

Sorry

**Comment by simonewebdesign** [comment]
Merged, thank you!

**Comment by sleipnir** [comment]
You are welcome. Thank you

**Pull request merged**
