### PR TITLE
added Elixir Forum

### PR DESCRIPTION
**Pull request by mackenza**

### CODE REVIEW

**Comment by h4cc** [comment]
The order is not alphabetic. "Elixir forum" comes later.

**Comment by mackenza** [comment]
sorry, the symbols threw me off (like `#`). I didn't realize you had this in a CI job check... the order was "in spirit" alphabetic but not strictly so ;)

**Comment by AstonJ** [comment]
Hi @mackenza - thanks for submitting the Elixir Forum :+1:  could you move it under the Slack channel though please? The others were submitted first so it is only fair they appear higher up the list - and I think this is what @h4cc is highlighting. 

We also need a space in-between 'Elixir' and 'Forum', so it reads [Elixir Forum]

Thanks for helping spread the word! :-)

**Comment by mackenza** [comment]
No, that's not what is being asked for. There is a build process that checks alphabetical order. So it will fail if you don't follow alphabetic order, regardless of when the link was added. 

I can add the space, which I guess will put it last. I was just following the convention I saw... I.e. ElixirSlack - there is no reason it has no space

**Comment by AstonJ** [comment]
Ah right, my apologies :blush:

**Comment by mackenza** [comment]
that was hard... seriously, I have done PRs a 100 times more complicated than this we fewer mistakes/commits... I think I need to go back to grade school to learn my alphabet :dancer:

**Comment by h4cc** [comment]
Thanks guys! :D

**Pull request merged**
