### PR TITLE
added githubissues

### PR DESCRIPTION
**Pull request by Kentoseth**
Add Package "githubissues"

##Added to readme file

Resolves "#2457"

##Commit message
Add githubissues

### CODE REVIEW

**Comment by Kentoseth** [comment]
Upon acceptance, please close #2457

**Comment by fladson** [comment]
Thanks for the contribution @Kentoseth 
But for acceptance, please make an individual pull request for each suggestion, as pointed out on the [contribution guidelines](https://github.com/h4cc/awesome-elixir/blob/master/.github/CONTRIBUTING.md)

**Comment by Kentoseth** [comment]
@fladson That is what I initially did, but it seems that when I tried to add each PR separately, github decided to merge them into 1 PR.

**Comment by fladson** [comment]
@Kentoseth I see, I was going to to it for you but it seems that the package no longer exists, I'm getting a 404 at `https://github.com/PatNowak/GithubIssues-Elixir`

**Comment by fladson** [comment]
@Kentoseth I'll close this, can you submit another PR adding just the `phoenix_gen_webpack`?

**Pull request closed without merging**
