### PR TITLE
Add Package Cronex

### LINKED ISSUE #3266: Evaluate Package "cronex"
Evaluate "cronex" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/cronex

Description: 
A cron like system built with elixir

This is a autogenerated issue, because the packages was added on hex.pm.

### PR DESCRIPTION
**Pull request by jbernardo95**
Resolves #3266

### CODE REVIEW

**Comment by fladson** [comment]
Thanks for the contribution @jbernardo95 
It needs to be in alphabetic order 😁

**Comment by jbernardo95** [comment]
@fladson My bad x)

Is this alphabetic ordering requirement written in any place ? I read the `CONTRIBUTING.md` and didn't catch anything ...

**Comment by fladson** [comment]
@jbernardo95 no problem 😁 

check https://github.com/h4cc/awesome-elixir/blame/master/.github/CONTRIBUTING.md#L32

**Comment by jbernardo95** [comment]
@fladson It is indeed ! (didn't read until the end)

**Pull request merged**
