### PR TITLE
Remove vulvapi, vulvex, dicks

### PR DESCRIPTION
**Pull request by smoynes**
vulvapi and vulvex are dead links. All three are not awesome.

### CODE REVIEW

**Comment by ShadowBan** [comment]
vulvapi and vulvex are working links now bitbucket had some down time.

However :+1: to getting rid of these links.  Even though they are properly marked in the fun section... they are just kind of childish.

**Comment by h4cc** [comment]
At start these projects could be used a simple examples, but resources for that have emerged now.
Elixir may be recognized more "adult", right.

**Comment by Annwenn** [comment]
I totally recognize that those projects are childish. I started them when I was ~18 and they were totally "for fun". 

>Elixir may be recognized more "adult"

That's some pretty unfair statement considering that the majority of Elixir developers isn't *that* old and that the language itself appeared in 2012…

**Comment by h4cc** [comment]
@Annwenn I think the therm 'recognized more "adult"', is not about the developers or the language. Beeing seen as an adult by others can be achieved with responsible and liable behavior of the Core-Team/Community.

On the other hand this awesome-list has also a documentary character and represents the current state of the elixir ecosystem.

I am personally not sure if i am :+1:  or :-1: on this. Any other views/ideas?

**Comment by nirev** [comment]
I'm against leaving them for the sole reason that they might offend/push away some people. Yes, they are childish and might be fun for *most* developers, but I think they go against the kind of community we should build.

So :-1: for keeping them.

**Comment by revdan** [comment]
I think the code of conduct is pretty clear: https://github.com/elixir-lang/elixir/blob/master/CODE_OF_CONDUCT.md

**Comment by Annwenn** [comment]
@h4cc yeah @revdan is right.

**Comment by h4cc** [comment]
Thanks for the Feedback.
Closing here now.

**Pull request merged**
