### PR TITLE
Add Package ExGtin to Validation Section

### PR DESCRIPTION
**Pull request by cdesch**
Adding the new Hex Package [ExGtin](https://github.com/kickinespresso/ex_gtin) to the validation section

Make sure you have the following format

##Title

Add Package ExGtin to Validation Section

##Description

Add Package "ex_gtin" to the Validations Section of the Library

This Library does GTIN code validation. 

GitHub Link: [ExGtin](https://github.com/kickinespresso/ex_gtin) 
HexDocs Link: [ex_gtin](https://www.hex.pm/packages/ex_gtin)

There is no issue number current open. 

##Commit message

Add ex_gtin library

### CODE REVIEW

**Comment by cdesch** [comment]
I'm not exactly sure what to do with this failed check within the Travis CI. Is this something I need to fix within the library I'm submitting? Any guidance appreciated.

**Comment by fladson** [comment]
@cdesch nothing wrong with the library itself, you just need to put the new entry in alphabetic order

**Comment by cdesch** [comment]
Will do. Let me modift

**Comment by cdesch** [comment]
Should be good. I'll wait for the CI check to complete.

**Comment by cdesch** [comment]
thanks @fladson

**Pull request merged**
