### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by mattgreg**
add Ockam to list

### CODE REVIEW

**Comment by simonewebdesign** [comment]
I get it's a suite of tools, but could you pick only one category?

**Comment by mattgreg** [comment]
@simonewebdesign Thanks for putting this list together.

**Comment by simonewebdesign** [comment]
> @simonewebdesign Thanks for putting this list together.

Thank you for contributing to it!

By the way you'll need to add a dot at the end of the sentence for the CI to pass!

**Comment by simonewebdesign** [comment]
Hmm, okay this is weird:

```
** (RuntimeError) Line does not match format: '[Ockam](https://github.com/ockam-network/ockam) — A suite of tools, programming libraries and infrastructure that make it easy to build devices that communicate securely, privately and trustfully with cloud services and other devices. [Docs](https://www.ockam.io/learn/concepts/).' Is there a dot at the end?
    check.exs:32: Awesome.parse_line/1
    check.exs:224: Awesome.validate_list_item/1
    check.exs:213: anonymous fn/2 in Awesome.check_list/1
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    check.exs:213: Awesome.check_list/1
    check.exs:192: Awesome.iterate_content/1
    check.exs:117: Awesome.test_file/1
The command "mix run check.exs" exited with 1.
```

The regex in [check.exs] might need a fix. Any ideas? 

[check.exs]: https://github.com/h4cc/awesome-elixir/blob/master/tests/check.exs#L27-L28

**Comment by simonewebdesign** [comment]
Oh, I think it's the em dash. Can you replace it with a regular dash please - see screenshot:

dash

**Comment by simonewebdesign** [comment]
Just needs to be ordered alphabetically, then it's good to go 👍🏼

**Comment by mattgreg** [comment]
doh. `O` comes after `p`. 😬

**Pull request merged**
